backend:
    name: git-gateway
    branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://callowhillwebdesigns.com/assets/svgs/logo.svg

media_folder: "src/assets/images/blog"
public_folder: "/assets/images/blog"

collections:
    - name: "blog"
      label: "Blog"
      folder: "src/content/blog"
      create: true
      slug: "{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "URL Slug",
                name: "url",
                widget: "string",
                hint: 'Specify where the page will be written to. If you use "Blog Post", the post will be accessible from "blog/blog-post"',
            }
          - { label: "Description", name: "description", widget: "string" }
          - { label: "Author", name: "author", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
          - { label: "Featured Image", name: "image", widget: "image" }
          - { label: "Image Caption", name: "imageAlt", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
    
     # SETTINGS CONFIG
    - label: Settings
      name: settings
      delete: false
      editor:
          preview: false
      files:
          - label: Website Settings
            name: website_settings
            file: src/_data/client.json
            description: Allows a client to update their own contact information, through the default client.json file
            fields:
                - label: Business Name
                  name: name
                  widget: string
                  summary: Used in browser tab and sharing links

                - label: Email
                  name: email
                  widget: string
                  summary: Main email for customers to contact you

                - label: Unformatted Telephone
                  name: phoneForTel
                  widget: string
                  summary: Used for clickable links to phone. Enter in format xxx-xxx-xxxx

                - label: Formatted Telephone
                  name: phoneFormatted
                  widget: string
                  summary: Used for display on website. Enter in your preferred format

                - label: Address
                  name: address
                  widget: object
                  collapsed: true
                  fields:
                      - label: Address Line One
                        name: lineOne
                        widget: string

                      - label: Address Line Two
                        name: lineTwo
                        widget: string

                      - label: City
                        name: city
                        widget: string

                      - label: State
                        name: state
                        widget: string

                      - label: Zip Code
                        name: zip
                        widget: string

                      - label: Google Maps Link
                        name: mapLink
                        widget: string
                        summary: Provide a Google Maps share link to guide visitors to your physical locations

                - label: Social Media
                  name: social
                  widget: object
                  collapsed: true
                  fields:
                      - label: Facebook
                        name: facebook
                        widget: string

                      - label: Twitter
                        name: twitter
                        widget: string

                      - label: Instagram
                        name: instagram
                        widget: string

                      - label: Youtube
                        name: youtube
                        widget: string
                        
    # PRODUCTS CONFIG
    - label: Products
      name: products
      delete: false
      editor:
          preview: false
      files: 
        - label: Product Items
          name: product_items
          file: src/content/products/products.json
          fields:
            - label: Categories
              name: categories
              label_singular: Category
              widget: list
              fields:
                - { label: Category, name: category_name, widget: string, hint: "Rosin, Solventless, Vapes, etc." }
                - { label: Category Description, name: category_desc, widget: string }
                - label: Items
                  name: items
                  label_singular: Item
                  widget: list
                  summary: "{{fields.item_name}}"
                  fields:
                    - { label: Item Name, name: item_name, widget: string }
                    - { label: Item Description, name: item_desc, widget: string }
                    - { label: Item Image, name: item_image, widget: image }
                    - { label: Tags, name: item_tags, widget: list, default: ["product"] }